# Generated by Django 4.0.1 on 2022-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
