# Generated by Django 4.0.1 on 2022-01-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UpcomingFixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteamup', to='base.team')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeamup', to='base.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayedFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('home_shots_on_goal', models.IntegerField()),
                ('away_shots_on_goal', models.IntegerField()),
                ('home_total_shots', models.IntegerField()),
                ('away_total_shots', models.IntegerField()),
                ('home_fouls', models.IntegerField()),
                ('away_fouls', models.IntegerField()),
                ('home_corner_kicks', models.IntegerField()),
                ('away_corner_kicks', models.IntegerField()),
                ('home_offsides', models.IntegerField()),
                ('away_offsides', models.IntegerField()),
                ('home_ball_possesion', models.IntegerField()),
                ('away_ball_possesion', models.IntegerField()),
                ('home_yellow_cards', models.IntegerField()),
                ('away_yellow_cards', models.IntegerField()),
                ('home_red_cards', models.IntegerField()),
                ('away_red_cards', models.IntegerField()),
                ('home_total_passes', models.IntegerField()),
                ('away_total_passes', models.IntegerField()),
                ('home_passes_accurate', models.IntegerField()),
                ('away_passes_accurate', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteampl', to='base.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeampl', to='base.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
            ],
        ),
    ]
