# Generated by Django 4.0.1 on 2022-01-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_team_icon_upcomingfixtures_playedfixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='form',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_diff',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league_position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
    ]
