# Generated by Django 4.0.1 on 2022-01-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_standings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('referee', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='base.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='base.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='upcomingfixtures',
            name='awayteam',
        ),
        migrations.RemoveField(
            model_name='upcomingfixtures',
            name='hometeam',
        ),
        migrations.RemoveField(
            model_name='upcomingfixtures',
            name='league',
        ),
        migrations.RemoveField(
            model_name='player',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lastname',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlayedFixture',
        ),
        migrations.DeleteModel(
            name='UpcomingFixtures',
        ),
    ]
