# Generated by Django 4.0.1 on 2022-01-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_fixtures_away_goals_alter_fixtures_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturesStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeShotsonGoal', models.IntegerField()),
                ('awayShotsonGoal', models.IntegerField()),
                ('homeTotalShots', models.IntegerField()),
                ('awayTotalShots', models.IntegerField()),
                ('homeFouls', models.IntegerField()),
                ('awayFouls', models.IntegerField()),
                ('homeCorner', models.IntegerField()),
                ('awayCorner', models.IntegerField()),
                ('homeYellow', models.IntegerField()),
                ('awayYellow', models.IntegerField()),
                ('homeRed', models.IntegerField()),
                ('awayRed', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_teamFix', to='base.team')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fixtures')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teamFix', to='base.team')),
            ],
        ),
    ]
